### ISSUE TITLE
Editor appears dirty when changed in another window

### ISSUE THREAD

**Issue by bpasero** [hediet/vscode-drawio#215] opened 2021-03-19 07:16 UTC
From https://github.com/microsoft/vscode/issues/119060

Steps to Reproduce:

1. install `hediet.vscode-drawio` extension
2. create a new draw IO diagram in a folder
3. select "Duplicate as workspace in new window"
4. open that diagram also in that second window
5. modify the diagram in first window

=> 🐛 the diagram nicely updates in the second window but appears as dirty somehow

I think this issue originates from the fact that there is a `applyWorkspaceEdit` here:

https://github.com/hediet/vscode-drawio/blob/19d39e69e836da5d8978bef0b538bc93a44ace66/src/DrawioEditorProviderText.ts#L177

**Comment by hediet** [comment] 2021-03-19 09:28
Hi Ben! Sorry for the confusion this bug caused and thanks for reporting it!

The applyEdit is actually required for custom editors to save their changes.
However, I also think the bug is not caused by vscode but rather by drawio not being idempotent: Somehow, it sometimes reports a real text change directly after loading. I already do some normalization (like removing the timestamp from the document and reformatting the xml), but apparently it is not enough.

**Comment by bpasero** [comment] 2021-03-19 09:44
@hediet yeah no worries, I am now more involved with custom editors in VSCode lately and wanted to give your extension a good test because it follows the custom text based approach that I am mainly interested in how it behaves. For example https://github.com/microsoft/vscode/issues/119059 is something I only now discovered and it shows an issue rather in VSCode that I should be able to resolve. 

I think you probably need some way of distinguishing between a user edit in the DrawIO editor and a file change event from disk.

**Comment by hediet** [comment] 2021-07-11 17:34
Should be fixed now (fix available in the insiders release).

**Closed** 2021-07-11 17:36 UTC
