### ISSUE TITLE
code link couldn't be activated

### ISSUE THREAD

**Issue by quax06** [hediet/vscode-drawio#239] opened 2021-07-09 08:54 UTC
Hi,
I do have problems to activate the code link feature.
When clicking on the icon I get this message:
"Running the contributed command: 'hediet.vscode-drawio.toggleCodeLinkActivation' failed."

Just starting with VScode and making some tests, if it fullfill our requirements.

Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Datum: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
Betriebssystem: Windows_NT x64 10.0.19043

drawio Version 1.5.0

Best regards..

**Comment by hediet** [comment] 2021-07-09 09:24
I cannot reproduce. Can you open the VS Code dev tools and see if there are any errors?

**Comment by quax06** [comment] 2021-07-09 09:31
I would apreciate any hints to do this

**Comment by hediet** [comment] 2021-07-09 09:33
VS Code -> Help -> Toggle Developer Tools

**Comment by quax06** [comment] 2021-07-09 09:37
Got it!
Any further information where I have to look at?

**Comment by quax06** [comment] 2021-07-09 09:39
I found this:

Running the contributed command: 'hediet.vscode-drawio.toggleCodeLinkActivation' failed.
onDidChangeNotification @ workbench.desktop.main.js:741
(anonymous) @ workbench.desktop.main.js:741
fire @ workbench.desktop.main.js:60
addNotification @ workbench.desktop.main.js:741
error @ workbench.desktop.main.js:1872
executeCommand @ workbench.desktop.main.js:2009
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
executeCommand @ workbench.desktop.main.js:2009
(anonymous) @ workbench.desktop.main.js:2009

**Comment by hediet** [comment] 2021-07-09 09:41
Hmm, that is not helpful. Can you reinstall the extension?

**Comment by quax06** [comment] 2021-07-09 09:43
Yes I can, but to be honest : I did this already several times. 
But I will do it again.

**Comment by hediet** [comment] 2021-07-09 09:47
Then it probably won't make a difference.

I'm sorry, I don't now how I can help you, as it works for me.

Maybe it is another extension? If you have time, you could try disabling all other extensions (there should be a command for that).

**Comment by quax06** [comment] 2021-07-09 09:59
I deactivated all except the german language pack ...   :-)
deactivated, uninstall, reinstall drawio again, but nothing changes..

**Comment by hediet** [comment] 2021-07-09 10:01
Very interesting, now I can reproduce. I will look into this today/tomorrow!

**Comment by quax06** [comment] 2021-07-09 10:06
Good luck for your investigation.

**Comment by hediet** [comment] 2021-07-09 10:10
Ok I found my issue. If this is the underlying issue I got super lucky finding this particular bug which I would never have spotted otherwise.

Can you check your settings.json if it is well formed an has no syntax errors?

**Comment by quax06** [comment] 2021-07-09 10:34
I found this
![2021-07-09 12_31_53-Window](https://user-images.githubusercontent.com/87175462/125065232-e0c87980-e0b1-11eb-8132-f44325895b58.gif)

**Comment by hediet** [comment] 2021-07-09 10:42
Yep, can you repair the syntax of that file?
Just remove the last two closing braces.

Then it should workt.

**Comment by quax06** [comment] 2021-07-09 10:48
Now it works...
Thanks for your help and for writing this extension.
I will go on now with my orignal testings.

Viele Grüße aus Straubenhardt

**Comment by hediet** [comment] 2021-07-09 10:52
Yeah, I got really lucky running into the same issue.
Otherwise I would have never gotten the idea that this could be the reason.

Grüße aus Karlsruhe

**Closed** 2021-07-09 11:56 UTC
Labels: bug
