### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by cgyFight** [hediet/vscode-drawio#249] opened 2021-07-14 11:32 UTC
i got an problem with:"Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.."

please help me. my os was mac. vscode version was 1.58.0

![image](https://user-images.githubusercontent.com/13238736/125614879-58356cb4-2c48-4ae3-8db1-6e6975385d93.png)

**Comment by hediet** [comment] 2021-07-14 11:34
Duplicate of #237. See https://github.com/microsoft/vscode/issues/122951.

**Closed by hediet** 2021-07-14 11:34 UTC

**Comment by cgyFight** [comment] 2021-07-14 11:43
oh, no, i can open markdown file and preview it in vscode . it seem's not same as 122951

**Comment by hediet** [comment] 2021-07-14 11:48
Can you try out the luna paint extension and see if that one works?

**Comment by cgyFight** [comment] 2021-07-14 11:54
i can't open luan paint extension too

**Comment by cgyFight** [comment] 2021-07-14 11:56
And i launch vscode with "--no-sandbox" too, but it's no different

**Comment by hediet** [comment] 2021-07-14 11:56
Then it is not related to this extension. If you think it is not #122951, please open another issue in the VS Code repo.

**Comment by cgyFight** [comment] 2021-07-14 11:57
oh, tks, i'll try it

**Comment by eduncan911** [comment] 2021-07-22 23:29
As an update to #122951 ... They have made it even more confusing by separating Windows users from Linux users (and removing the Linux label).

So, if on windows: https://github.com/microsoft/vscode/issues/125951

If on Linux, go here: https://github.com/microsoft/vscode/issues/125993
