### ISSUE TITLE
Cannot open .drawio.png files

### ISSUE THREAD

**Issue by vbridger** [hediet/vscode-drawio#151] opened 2020-10-12 02:53 UTC
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..

Vscode Version: 1.50.0
Draw.io Integration Version: v1.0.1

**Comment by hediet** [comment] 2020-10-12 06:32
Duplicate of #127.

**Comment by hediet** [comment] 2020-10-12 06:33
Also possible duplicate of this:
https://github.com/microsoft/vscode/issues/108431

**Closed by hediet** 2020-10-12 06:33 UTC
