### ISSUE TITLE
Opening files can take up to several minutes. 

### ISSUE THREAD

**Issue by looeee** [hediet/vscode-drawio#14] opened 2020-05-11 13:28 UTC
Attached are two files.

* `coordinate_system.drawio` - usually loads in about 10 seconds. 
* `anisotropy.drawio` - timed with a stopwatch. Takes 3 minutes 15 seconds to load.  

The main difference between these files is the second one has a couple of embedded images. However, it's only ~80kb in size so this loading time seems very high. 

CPU use remains at 25% and memory around 170mb, for the ExtensionHost in VSCode process explorer. 

Both files load instantly on web and desktop draw.io clients. 

[drawio_test.zip](https://github.com/hediet/vscode-drawio/files/4609786/drawio_test.zip)

**Comment by hediet** [comment] 2020-05-11 13:41
Thanks for your test files! But I'm sorry, I cannot reproduce your issue. They open very quickly in VS Code on my machine [1]:

![cadc9194-481a-4da2-a13d-f69237bf3053](https://user-images.githubusercontent.com/2931520/81567971-657c1280-939d-11ea-8e58-106a8a88e51e.gif)

[1] Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 16 GB RAM

What are your specs?

**Comment by chuzarski** [comment] 2020-05-11 18:31
I also tried to reproduce this, both files opened pretty much instantly

OS: Debian GNU/Linux bullseye/sid x86_64 Kernel 5.6.0-1-amd64
AMD Ryzen 7 1700 @ 3.0GHz, 32GB RAM

**Comment by looeee** [comment] 2020-05-12 02:42
Core i5-6300 2.3ghz + 24gb ram. 
I doubt this is a specs issue though, as I mentioned, ram and cpu use both remain low. 

I've tested again after a system restart and behavior is the same. Could this be caused by another extension? Is there some way I can disable other extensions while leaving this one active?

**Comment by hediet** [comment] 2020-05-12 04:58
@looeee Thanks for looking into it. `Spell Right` seems to process the underlying xml of the draw io document. Since these documents can grow rather large, things can become slow.

Maybe Spell Right should just stop spell checking if the document size exceeds a specific threshold.
I think that's worth an issue in their repo!

**Comment by looeee** [comment] 2020-05-12 05:24
> Spell Right seems to process the underlying xml of the draw io

Hmm, I have set spell right to only process markdown, plaintext, and HTML in settings.json:

``` 
  "spellright.documentTypes": [
    "markdown",
    "plaintext",
    "html"
  ],
```

I thought maybe "HTML" catches all XML type documents, but even setting it to just "markdown" doesn't fix this. 

So it seems like this is a bug on their end. I'll report it over on the spell right repo.

**Comment by hediet** [comment] 2020-05-12 05:46
Thanks for opening an issue in the spellright repo! I'll close this one as there is likely nothing I can do on my end to fix it. Please reopen this issue if the spellright people indicate that there actually is something that I can do!

**Closed by hediet** 2020-05-12 05:46 UTC

**Comment by looeee** [comment] 2020-05-12 05:51
Will do! Thanks for the speedy response. 

And thanks for creating this extension, it's gonna improve my workflow in a big way ^_^

**Comment by hediet** [comment] 2020-05-12 06:21
Thank you! That's nice to hear ;) Please let me know if you have ideas how it can improve your workflow further!

**Comment by looeee** [comment] 2020-05-12 07:16
The biggest thing would be SVG support. 

Currently, I have a few hundred SVG files generated by the online draw.io app. 
To use this extension, I'll have to go through all of those and convert them back to  .drawio files. Then I'll have to maintain two versions of each: .svg which I use on my website, and .drawio for editing. 

It would be much better if I could just work with the SVGs directly.

**Comment by hediet** [comment] 2020-05-12 07:59
Well, I see that `.drawio.svg` is annoying, but it has some advantages:
* The drawio editor is not the default editor for all `*.svg` files (which would be equally annoying).
* It communicates that such a svg file is a source file, not an artifact as most svg files are.

You can easily configure VS Code to open `svg` files with drawio like this, though :
```
    "workbench.editorAssociations": [
        {
            "viewType": "hediet.vscode-drawio-text",
            "filenamePattern": "*.svg"
        }
    ],
```

**Comment by looeee** [comment] 2020-05-12 10:46
OK, that's good enough for me 👍
