### ISSUE TITLE
Standard BPMN 2.0 Shapes fail to load

### ISSUE THREAD

**Issue by LRelar** [hediet/vscode-drawio#238] opened 2021-07-02 12:01 UTC
+More Shapes->Business->BPMN 2.0
These shapes fail to load its group contents when trying to expand group.
The behavior depends on order you attempt to expand the group.
Trying to open BPMN 2.0 Tasks or BPMN 2.0 Choreographies foremost corrupts whole BPMN 2.0 Shapes set.

**Comment by anderskristian** [comment] 2021-07-15 17:36
This is exactly the problem that let me investigate drawio - and found out that there is a problem in this implementation

**Comment by hediet** [comment] 2021-07-15 19:00
> I don't have any clue on how identical these parts are in code version and https://github.com/jgraph/drawio

They should be identical. See the submodule `drawio` in https://github.com/hediet/vscode-drawio.

> I also see that the menu system is not identical - still I got no clue weather this is necessary to be different or it just happened

I had to remove dysfunctional menu items (such as print etc.).

If more people run into this particular issue, I will do a more depth investigation.

**Comment by anderskristian** [comment] 2021-07-15 20:53
Now I have "learned a little of how to build" - and it seems that elements are added as git submodules
It is a little strange that BPMN 2.0 is not in 1.6.6

Does the project miss a script to get the correct git submodules ???

**Comment by DanielTheCoder** [comment] 2021-07-20 15:38
I've the same issue that BPMN 2.0 Shapes are missing, using v1.6.1
![image](https://user-images.githubusercontent.com/161882/126353541-e581dce9-d849-4087-b5bc-d2feadce4dbd.png)

**Comment by aramera** [comment] 2021-07-25 13:27
Not only bpmn. I don't use draw.io to draw simple diagrams (in strictly defined notations only). Archimate 3.1 and other libraries don't work either. Also, adding a new library can break the display of an existing library. It will be very cool if you can fix everything )

**Comment by BartNetJS** [comment] 2022-05-10 07:22
Any update on this issue?
Would be cool if fixed.
Great tool!

**Comment by hediet** [comment] 2022-05-10 09:44
No updates, but will look into it soon!

**Comment by hediet** [comment] 2023-01-13 01:11
Duplicate of #354. Should be fixed in the insider version.

**Closed by hediet** 2023-01-13 01:11 UTC
Labels: bug, help wanted
