### ISSUE TITLE
Not opening file in vscode.

### ISSUE THREAD

**Issue by sannamalai176** [hediet/vscode-drawio#26] opened 2020-05-12 18:13 UTC
Hi

I installed the plugin and tried to open a .drawio file and vscode doesnt open the file.

VS Code : 1.45.0

**Comment by hediet** [comment] 2020-05-12 18:14
Can you post a video?

**Comment by sannamalai176** [comment] 2020-05-12 18:21
and also export to pdf is also not working.

**Comment by sannamalai176** [comment] 2020-05-12 18:22
sure. the other behavior of not opening, i observed in my other computer at work. vscode is opened as administrator as well.

**Comment by traits** [comment] 2020-05-13 10:21
> and also export to pdf is also not working.

I can confirm this (Windows 10, vscode portable). After pressing "Download" in the PDF Export dialog, nothing happens. The same for "Open in New Window"

**Comment by blaulan** [comment] 2020-05-14 06:11
I have a similar issue. After the extension was installed, I created a new file called "demo.drawio". Then I tried to open it but all I could see was a blank page. and meanwhile all keyboard shortcut seems stopped working when the file was opened.
![image](https://user-images.githubusercontent.com/1806122/81899004-6c4c9480-95ec-11ea-9ee0-b9d4bf2b495d.png)

**Comment by blaulan** [comment] 2020-05-14 06:13
> I have a similar issue. After the extension was installed, I created a new file called "demo.drawio". Then I tried to open it but all I could see was a blank page. and meanwhile all keyboard shortcut seems stopped working when the file was opened.
> ![image](https://user-images.githubusercontent.com/1806122/81899004-6c4c9480-95ec-11ea-9ee0-b9d4bf2b495d.png)

I'm on Mac and version of vscode is 1.45.0. The extension has been updated to the latest version 0.3.0.

**Comment by hediet** [comment] 2020-05-14 06:45
Does the extension not work at all or just on the very first opening?

**Comment by hediet** [comment] 2020-05-14 06:48
I have no idea what causes it, I don't know what exactly breaks (could be anything) and I cannot really reproduce it. This makes it incredibly hard to debug.

**Comment by blaulan** [comment] 2020-05-14 07:58
> Does the extension not work at all or just on the very first opening?

It doesn't work at all. I will try to install the extension on another computer to see if I can reproduce it.

**Comment by hediet** [comment] 2020-05-14 07:59
Do you use remote development or something like it?

**Comment by hediet** [comment] 2020-05-14 12:17
It would be super cool if a web/vscode developer on Mac could debug this!

**Comment by WuhenPhi** [comment] 2020-05-15 04:04
Restart VScode and reopen the file may help.

**Comment by blaulan** [comment] 2020-05-15 04:36
> Do you use remote development or something like it?

No I'm on a local machine. I tried install the extension on vscode-insiders and it works. Maybe the issue has something to do with the 1.45.0 version of vscode.

**Comment by hediet** [comment] 2020-05-15 07:05
Ah that's good news. It also means this is not a bug in my extension, otherwise it would not work in insiders, so I'll close this issue. If you think it is a bug that I can somehow fix, please comment here and reopen this issue!

**Closed by hediet** 2020-05-15 07:05 UTC
Labels: needs more info

**Comment by nichosap** [comment] 2023-07-05 11:33
I had the same issue. Problem was i had an error in the settings.json and it showed me also the blank screen. Once i fixed the settings.json everything worked as expected.
