### ISSUE TITLE
"More Shapes" selections do not all appear in the shapes sidebar palette

### ISSUE THREAD

**Issue by attentive** [hediet/vscode-drawio#294] opened 2022-01-28 01:53 UTC
Steps to repeat: 

1. Create a new .drawio diagram in VS Code
2. Use the "More Shapes …" dialog to enable BPMN 2.0 shapes for the diagram
3. Access two, three or more of the collapse controls for BPMN shapes that appear in the shapes palette
4. Not all expanded shape collections have content

The precise BPMN collections which are not correctly retrieved vary between reproductions of the issue. The screencap below shows a case where the "BPMN General" collection is loaded, but "Tasks", "Choreographies" and "Events" are not. The issue doesn't seem to affect the browser-hosted version of diagrams.net. 

![image](https://user-images.githubusercontent.com/50170/151473215-90c3e691-086d-4389-8ec4-3d67d1f68b33.png)

**Comment by NobuhikoAbe** [comment] 2022-02-13 13:33
In VS Code case
I have excluded shapes.min.js from the following files.

- dist/extension/index.js
- dist/extension/index.js.map

**Comment by linnjason678** [comment] 2022-03-29 11:42
> Steps to repeat:
> 
> 1. Create a new .drawio diagram in VS Code
> 2. Use the "More Shapes …" dialog to enable BPMN 2.0 shapes for the diagram
> 3. Access two, three or more of the collapse controls for BPMN shapes that appear in the shapes palette
> 4. Not all expanded shape collections have content
> 
> The precise BPMN collections which are not correctly retrieved vary between reproductions of the issue. The screencap below shows a case where the "BPMN General" collection is loaded, but "Tasks", "Choreographies" and "Events" are not. The issue doesn't seem to affect the browser-hosted version of diagrams.net.
> 
> ![image](https://user-images.githubusercontent.com/50170/151473215-90c3e691-086d-4389-8ec4-3d67d1f68b33.png)

**Comment by DanielTheCoder** [comment] 2022-06-08 10:57
I think it's the same problem as described here https://github.com/hediet/vscode-drawio/issues/238

**Comment by RicardoNoerr** [comment] 2022-06-08 12:47
> 

Yes, ut is

**Comment by hediet** [comment] 2023-01-13 01:11
Duplicate of #354. Should be fixed in the insider version.

**Closed by hediet** 2023-01-13 01:11 UTC
Labels: bug
