### ISSUE TITLE
Cannot get right math formula

### ISSUE THREAD

**Issue by dualer** [hediet/vscode-drawio#247] opened 2021-07-12 16:23 UTC
When I export some `.drawio` file to `.png` file, where some latex math formula, I cannot get right output. E.g. some output like
![test](https://user-images.githubusercontent.com/85242539/125322092-f4a10380-e36f-11eb-9e61-0e3584580aef.png)

which is not right. I have enabled `mathematical typesetting` option.

**Comment by hediet** [comment] 2021-07-12 16:48
Duplicate of #180.

**Closed by hediet** 2021-07-12 16:48 UTC
