### ISSUE TITLE
*.drawio.png not open

### ISSUE THREAD

**Issue by zsy619** [hediet/vscode-drawio#127] opened 2020-09-19 10:33 UTC
Unable to open '航院信息分类.drawio.png': Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..

file not open，but yesterday can open,why???

vscode info：
Version: 1.50.0-insider
Commit: 403a6895f401c397933ec5c4f7d89432a33509b6
Date: 2020-09-18T07:11:53.303Z (1 day ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by zsy619** [comment] 2020-09-19 10:52
for examples
![a drawio](https://user-images.githubusercontent.com/6278792/93665471-49a21f00-faa9-11ea-8fd9-f74a158f4b00.png)

**Comment by hediet** [comment] 2020-09-19 17:28
Can you zip the file and send me the zip file?
Also, you are using the insider version of VS Code. Can you try the stable build?

Thanks ;)

**Comment by zsy619** [comment] 2020-09-21 06:58
> Can you zip the file and send me the zip file?
> Also, you are using the insider version of VS Code. Can you try the stable build?
> 
> Thanks ;)

[Archive.zip](https://github.com/hediet/vscode-drawio/files/5253818/Archive.zip)
all *.drawio.png are not open.....

**Comment by zsy619** [comment] 2020-09-22 06:49
> Can you zip the file and send me the zip file?
> Also, you are using the insider version of VS Code. Can you try the stable build?
> 
> Thanks ;)

找到问题了吗？？？

**Comment by hediet** [comment] 2020-09-26 08:01
Not yet, I was/am very busy.

**Comment by zsy619** [comment] 2020-09-27 10:21
> Not yet, I was/am very busy.

when solution？？file not open，so bad~~~

**Comment by zsy619** [comment] 2020-09-27 10:22
> Not yet, I was/am very busy.

Unable to open '大赛管理系统.drawio.png': Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..

**Comment by hediet** [comment] 2020-09-27 11:28
> when solution？

I try to have a look at it next week, but I cannot promise anything as other projects currently have priority. Feel free to debug it yourself and open a pull request ;)

You could also [sponsor me on github](https://github.com/sponsors/hediet) to give me more motivation of maintaining this project!
I'm currently funded for 4h/month to work on all my open source projects ;)

**Comment by hediet** [comment] 2020-10-04 10:54
I can open all your files:

![image](https://user-images.githubusercontent.com/2931520/95012914-ba664100-063c-11eb-9156-8de3355e5cc7.png)

**Comment by zsy619** [comment] 2020-10-05 04:37
怎么回事呀

**Comment by zsy619** [comment] 2020-10-05 04:38
> 怎么回事呀

Unable to open '航院信息分类.drawio.png': Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..

**Comment by hediet** [comment] 2020-10-05 08:01
Sorry, I don't understand those characters (Chinese?).

Please record a gif so I can see what is going wrong. 
If I cannot reproduce it, it cannot fix it.

**Comment by zxl19** [comment] 2020-10-09 12:59
Hi @hediet !
Thank you for your excellent work! I encountered exactly the same problem as @zsy619 's just now. I guess it's because we used Chinese characters in file paths and filenames. I switched the file paths and filenames back to English and it worked out fine. I hope it would help you with this issue.

Best regards.

**Comment by hediet** [comment] 2020-10-09 13:37
Ah I see, so it is about the file names. None of the files in the zip file had those characters!

**Comment by zxl19** [comment] 2020-10-09 13:59
Hi @hediet ！
It could also be cout file paths. In my case, I created a `.drawio.png` file on my desktop **using an English filename** and everything seems fine. The problem occurred **after I moved the files to a directory named with Chinese characters**.

Best regards.

**Comment by hediet** [comment] 2020-10-11 15:39
This seems to work for me:

![image](https://user-images.githubusercontent.com/2931520/95682786-8ca66c80-0be7-11eb-9207-b9b4856058cb.png)

I'm using vscode 1.50.0. Also, I don't use `btoa` anywhere. I also don't send the filename to the webview. Maybe it is/was a VS Code issue?

[Seems like it is/was an VS Code issue](https://github.com/microsoft/vscode/issues/108431)!

Since I cannot reproduce your problem and it seems to happen for all extensions that provide a custom editor, I'm closing this issue. Please comment, if you find evidence that I can/need to do something.

**Closed by hediet** 2020-10-11 15:39 UTC
Labels: bug, will do for sponsorship
